### ISSUE TITLE
登录失败

### ISSUE THREAD

**Issue by littledogboy** [trytofix/hexo_weibo_image#2]
是不是微博更新了？  登录失败，还请指教是哪里的问题。 好想也会python啊

**Comment by buxiebug** [comment]
尝试登陆下网页版的微博，看看有没有问题．

**Comment by buxiebug** [comment]
我这边偶尔也有这种问题，登陆下网页版，重启下就好了．．．　具体问题我再看看

**Comment by EkkoG** [comment]
正则问题，剔除 html 字符的时候，不能匹配到多行，导致匹配失败，其实不是登录问题

已经发了 PR 修复该问题

https://github.com/trytofix/hexo_weibo_image/pull/3

**Comment by buxiebug** [comment]
多谢指出问题,好久没维护工程了,自我反省下~

**Comment by EkkoG** [comment]
我是昨天维护我的 Workflow 的时候发现这个问题的😂 https://github.com/cielpy/WeiboPictureWorkflow/commit/a0e81ed66f7a714f725bb85b971cb238a92c407c

对 python 还不是很熟，debug 了两小时

**Comment by trytofix** [comment]
最近一直在忙,就没时间看这个,长知识了

**Comment by buxiebug** [comment]
http://trytofix.github.io/2016/05/04/markdown%E4%BD%BF%E7%94%A8%E6%88%AA%E5%9B%BE%E4%BB%A5%E5%8F%8A%E5%9B%BE%E5%BA%8A%E4%BC%98%E5%8C%96%E5%86%99%E4%BD%9C%E4%BD%93%E9%AA%8C/  我自己也做了一个跟你功能比较相似的workflow,也是写markdown的时候觉得直接截图,粘贴图片地址比较方便,可以交流下

**Comment by EkkoG** [comment]
你博客的静态资源用的七牛，但是是 HTTP 的，Github 给 *.github.io 开了 HTTPS，你博客的样式都没了- -

**Comment by buxiebug** [comment]
我用的是http呢, 别用https访问...

**Comment by tinymind** [comment]
登录返回4091怎么办呢，需要验证码……

**Comment by EkkoG** [comment]
出现验证码的话比较麻烦，要有一个交互输入验证码，加上提交验证码等，暂时只能换账号或者等段时间再登录了:(

**Comment by littledogboy** [comment]
可以的老哥 稳！！！！
